return 
{
	['EventCenter'] = 'app.utils.event.EventCenter',
	['SrcMgr'] = 'app.manager.SrcMgr',
	['DataBase'] = 'app.data.DataBase',
	['ViewMgr'] = 'app.manager.ViewMgr',
	['DataMgr'] = 'app.manager.DataMgr',
	['ResMgr'] = 'app.manager.ResMgr',
	['TableExt'] = 'app.utils.extend.TableExt',
	['MainScene'] = 'app.MainScene',
	['MyApp'] = 'app.MyApp',
	['RenderMgr'] = 'app.manager.RenderMgr',
	['ViewBase'] = 'app.view.ViewBase',
	['RenderBase'] = 'app.render.RenderBase',
},
